services:
  web:
    image: ghcr.io/nicekrassss/winter-cms-devops:latest
    build: .
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: winter
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: winter
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
